"use client";
import {useEffect,useState} from "react";
type User={id:number;name:string;username:string;avatar_url:string;verified:boolean;role:string};
type Snip={id:number;title:string;description:string;language:string;locked:boolean;user_id:number;name:string;username:string;avatar_url:string;verified:boolean;likes:number;comments:number;liked:boolean};
const api=async(url:string,opt?:RequestInit)=>{const r=await fetch(url,opt);const j=await r.json();if(!r.ok)throw new Error(j.error||"Terjadi kesalahan");return j};
export default function App(){const [user,setUser]=useState<User|null>(null),[items,setItems]=useState<Snip[]>([]),[modal,setModal]=useState<string|null>(null),[msg,setMsg]=useState("");
const load=()=>Promise.all([api('/api/me').then(x=>setUser(x.user)),api('/api/snippets').then(setItems)]);useEffect(()=>{load()},[]);
async function auth(e:any,type:string){e.preventDefault();setMsg('');const fd=new FormData(e.currentTarget);try{await api('/api/auth/'+type,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});setModal(null);await load()}catch(e:any){setMsg(e.message)}}
async function create(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/api/snippets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});setModal(null);await load()}catch(e:any){setMsg(e.message)}}
return <main><header><a className="brand">&lt;/&gt; CodeSphere</a><nav><a href="#feed">Jelajah</a>{user&&<a href="/profile">Profil</a>}{user?.role==='owner'&&<a href="/admin">Kendali</a>}</nav><div className="actions">{user?<><button className="ghost" onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()}}>Keluar</button><button onClick={()=>setModal('create')}>+ Upload code</button></>:<><button className="ghost" onClick={()=>setModal('login')}>Masuk</button><button onClick={()=>setModal('register')}>Daftar</button></>}</div></header>
<section className="hero"><div><span className="pill">Platform developer Indonesia</span><h1>Bagikan kode.<br/><em>Bangun reputasi.</em></h1><p>Publikasikan snippet, diskusikan solusi, dan kirim request langsung ke developer yang tepat.</p><button onClick={()=>setModal(user?'create':'register')}>Mulai berbagi kode</button></div><div className="codecard"><div className="dots">● ● ●</div><pre><b>const</b> community = {'{'}<br/>  creators: <i>true</i>,<br/>  collaboration: <i>true</i>,<br/>  control: <span>"yours"</span><br/>{'}'};</pre></div></section>
<section id="feed" className="content"><div className="sectionhead"><div><small>COMMUNITY FEED</small><h2>Snippet terbaru</h2></div><input placeholder="Cari judul atau bahasa..." onChange={e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.snippet').forEach((el:any)=>el.style.display=el.innerText.toLowerCase().includes(q)?'':'none')}}/></div><div className="grid">{items.map(s=><article className="snippet" key={s.id}><div className="author"><img src={s.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${s.username}`}/><div><strong>{s.name} {s.verified&&<span className="check">✓</span>}</strong><small>@{s.username}</small></div><span className="lang">{s.language}</span></div><h3>{s.locked&&'🔒 '}{s.title}</h3><p>{s.description||'Tanpa deskripsi.'}</p><div className="meta"><button onClick={async()=>{try{await api(`/api/snippets/${s.id}/like`,{method:'POST'});load()}catch(e:any){alert(e.message)}}}>♥ {s.likes}</button><span><a href={`/snippet/${s.id}`}>💬 {s.comments} · Lihat kode</a>{user&&user.id!==s.user_id&&<button className="requestbtn" onClick={async()=>{const message=prompt(`Kirim request ke @${s.username}`);if(message){try{await api("/api/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({developer_id:s.user_id,message})});alert("Request terkirim")}catch(e:any){alert(e.message)}}}}>Request</button>}</span></div></article>)}</div></section>
<footer>CodeSphere · Kendali tetap di tangan pemilik platform.</footer>
{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal"><button className="x" onClick={()=>setModal(null)}>×</button>{modal==='login'&&<><h2>Selamat datang kembali</h2><form onSubmit={e=>auth(e,'login')}><input name="identity" placeholder="Email atau username" required/><input name="password" type="password" placeholder="Password" required/><button>Masuk</button></form></>}{modal==='register'&&<><h2>Buat akun baru</h2><form onSubmit={e=>auth(e,'register')}><input name="name" placeholder="Nama lengkap" required/><input name="username" placeholder="Username" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password minimal 6 karakter" required/><button>Daftar</button></form></>}{modal==='create'&&<><h2>Upload snippet</h2><form onSubmit={create}><input name="title" placeholder="Judul snippet" required/><div className="row"><input name="language" placeholder="Bahasa: JavaScript"/><input name="password" type="password" placeholder="Password akses (opsional)"/></div><textarea name="description" placeholder="Deskripsi singkat"/><textarea name="code" className="codeinput" placeholder="Tempel kode di sini..." required/><button>Publikasikan</button></form></>}<p className="error">{msg}</p></div></div>}</main>}
